# -*- coding: utf-8 -*-
"""snake, water, gun(rock, paper, and seccior) game.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zofmVUemdkKUVw2wVqU07g8zP-ldhG29
"""

import random



won = 0
lose = 0
#loop for multiple tries
for i in range(2):

  #user input
  user=input("chose the A,B or C:\nA)Snake \nB)Water \nC)Gun ").upper()
  user_input=["A","B","C"]

  #computer input
  computer_input=random.choice(user_input)

  #validate user input
  while user not in user_input:
    print("\ninvalid input \nselect A,B,C\n")
    user=input("chose the A,B or C:\na A)Snake \nB)Water \nC)Gun").upper()

  # game logic
  if user== computer_input:
      print("\nDraw\n")
  elif (user=="A" and computer_input=="B") or (user=="B" and computer_input=="C") or (user=="C" and computer_input=="A"):
      print("\nYou won\n")
      won += 1
  elif (user=="A" and computer_input=="C") or (user=="B" and computer_input=="A") or (user=="C" and computer_input=="B"):
      print("\nYou lose\n")
      lose += 1


# desicion
conclusion = "You won" if won > lose else "You lose" if won < lose else "Draw"
print(f"Your total won is {won} times and total lose is {lose} times So {conclusion}")